version: "3.8"

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/share/nginx/html # Mount local client folder
    ports:
      - "8080:80"

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app # Mount local server folder
    ports:
      - "8000:8000"
